spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/socialMedia_test
    username: postgres
    password: deniscaligula
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect